"""Write docs/binary_fraction/numbers.tex (all numbers and the two tables of the binary-fraction write-up) from
results/partB_v4/upper_limits.csv, upper_limits_meta.json and results/partC_v4/shortlist.csv.
Usage: python scripts/writeup_numbers.py
"""
import json
from pathlib import Path

import pandas as pd


def pct(x, nd=1):
    return f"{100 * x:.{nd}f}\\%"


def main():
    T = pd.read_csv("results/partB_v4/upper_limits.csv").set_index(["M2", "P"])
    meta = json.loads(Path("results/partB_v4/upper_limits_meta.json").read_text())
    r = T.loc[("0.4-1.5", "1000-10000")]
    lines = {
        "NCAND": f"{int(meta['k'])}", "KNINETYFIVE": f"{meta['k95']:.0f}", "EXPECTED": f"{meta['b']:.0f}",
        "EPS": pct(r.eps_final, 0), "EPSLOWP": pct(T.loc[("0.4-1.5", "300-1000")].eps_final, 0),
        "EPSLOWM": pct(T.loc[("0.15-0.4", "3000-10000")].eps_final, 0),
        "FMAX": pct(r.f_max_final), "FMAXLONG": pct(T.loc[("0.4-1.5", "3000-10000")].f_max_final),
        "FMAXLOWM": pct(T.loc[("0.15-0.4", "3000-10000")].f_max_final),
        "FMAXBKG": pct(r.f_max_final_bkgsub), "FMAXBKGHALF": pct(r.f_max_final_bkgsub_b_half),
        "EPSRAW": pct(r.eps, 1), "EPSOLD": pct(r.eps_lc_sims_x_alpha, 1),
    }
    ser, lc = r.eps_series_sims, r.eps_lc_sims
    low = T.loc[("0.4-1.5", "300-1000")]
    lines["VALIDATION"] = (f"injecting the same orbits at the season level into simulated stars without timing noise gives an efficiency "
                           f"{ser:.3f} vs {lc:.3f} for the light-curve-level injection ($0.4$--$1.5\\,\\Msun$, 1{{,}}000--10{{,}}000\\,d) and "
                           f"{low.eps_series_sims:.3f} vs {low.eps_lc_sims:.3f} at 300--1{{,}}000\\,d. The real-star efficiencies are therefore multiplied "
                           f"by this ratio in each bin (capped at 1; conservative).")
    rows = []
    for m2 in ("0.4-1.5", "0.15-0.4", "0.05-0.15"):
        for P in ("300-1000", "1000-3000", "3000-10000", "1000-10000"):
            x = T.loc[(m2, P)]
            f = x.f_max_final
            fs = "--" if not (f < 1) else pct(f)
            fb = "--" if not (f < 1) else pct(x.f_max_final_bkgsub)
            rows.append(f"{m2.replace('-', '--')} & {P.replace('-', '--')} & {int(x.n_inj)} & {x.eps_final:.3f} "
                        f"({x.eps_lo * x.smear_corr:.3f}--{x.eps_hi * x.smear_corr:.3f}) & {fs} & {fb} \\\\")
    table = ("\\begin{tabular}{llrlrr}\\toprule\n$M_2$ [\\Msun] & $P_{\\rm orb}$ [d] & injections & $\\varepsilon$ (68\\%) & "
             "$f_{\\max}$ & $f_{\\max}^{\\rm bkg}$ \\\\\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\\end{tabular}\n"
             "\\par\\smallskip{\\footnotesize ``--'': no useful limit ($f_{\\max}>100\\%$).}")
    S = pd.read_csv("results/partC_v4/shortlist.csv")
    S = S[S.shortlist]
    srows = []
    for x in S.itertuples():
        test = "blind" if x.blind_pass else "split"
        srows.append(f"{x.ogle_id.replace('OGLE-LMC-RRLYR-', '')} & {x.P_kep / 365.25:.1f} & {x.e_kep:.2f} & {x.M2min_kep:.2f} & "
                     f"{x.K1_kep:.1f} & {test} & {'yes' if x.eccentric else 'no'} & {'MACHO+OGLE' if x.has_M else 'OGLE'} \\\\")
    stable = ("\\begin{tabular}{lrrrrlll}\\toprule\nOGLE-LMC-RRLYR- & $P$ [yr] & $e$ & $M_{2,\\min}$ [\\Msun] & $K_1$ [\\kms] & "
              "prediction & eccentric & data \\\\\\midrule\n" + "\n".join(srows) + "\n\\bottomrule\\end{tabular}")
    out = [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in lines.items()]
    out.append("\\newcommand{\\TABLE}{" + table + "}")
    out.append("\\newcommand{\\SHORTTABLE}{" + stable + "}")
    Path("docs/binary_fraction/numbers.tex").write_text("% generated by scripts/writeup_numbers.py - do not edit\n" + "\n".join(out) + "\n")
    print("\n".join(out[:15]))


if __name__ == "__main__":
    main()
